version: "3.9"

services:
  sevaro-bot:
    build: .
    container_name: sevaro-bot
    ports:
      - "3267:3267"
    volumes:
      - ./okta_state.json:/app/okta_state.json
    environment:
      - TELEGRAM_BOT_TOKEN="8160686991:AAGo5m6aj8BZ7kmfo4phgOojLGlyNkgkePg"
      - TELEGRAM_CHAT_ID="8492458042"
    restart: unless-stopped
